# NUMPY 

So lets have a basic exercise on numpy. 

In [ ]:
import numpy as np 

#### create an array of 10 tens 

In [ ]:
# your code here-
np.ones(10, dtype=np.int64)*10

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

#### Create an array of all the odd integers from 100 to 200

In [ ]:
# your code here-
np.arange(101,200,2)

array([101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125,
       127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151,
       153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177,
       179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199])

#### Create a 3x3 identity matrix

In [ ]:
# your code here-
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### write a code that gives the output given below
 ** *Note! In order to not lose the output, make sure you don't code in the cell that is directly above the plot, there is an extra cell above that one which won't overwrite that plot!* **



In [ ]:
data = [[5*row+i for i in range(1,6) ] for row in range(5)]

np.array(data)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# your code here-


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Create a 4X4 matrix with values starting from 0

In [ ]:
# your code here-
np.matrix([[0 for i in range(4)]for _ in range(4)])


matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

#### Use NumPy to generate an array of 9 random numbers sampled from a standard normal distribution

In [ ]:
# your code here-
s = np.random.normal(0, 1, 9)
s

array([ 1.31971683,  0.13062107, -1.36330978, -0.5405284 , -1.29519857,
       -1.4137748 ,  1.56558506,  0.98559384,  0.08752179])

In [ ]:
j=np.arange(12,24).reshape(3,4)
j

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### on the given above array 'j' , perform the given questions. 

#### 1. Get the standard deviation of the values in mat

In [ ]:
# your code here-
np.std(j)

3.452052529534663

#### 2. Get the sum of all the columns in mat

In [ ]:
# your code here-
j.sum(axis=0)

array([48, 51, 54, 57])

#### 3. write a code that gives the following output given below.
** *Note! In order to not lose the output, make sure you don't code in the cell that is directly above the plot, there is an extra cell above that one which won't overwrite that plot!* **

In [25]:

np.array([[i]for i in j[:,1]])

array([[13],
       [17],
       [21]])

In [ ]:
# your code here-


array([[13],
       [17],
       [21]])

#### 4. Get the sum of all the values in mat

In [21]:
# your code here-
j.sum()

210

# GLAD YOU COMPLETED THIS PART, GOOD LUCK AHEAD!!